#!/bin/bash
# this is hbtgm
# this script makes main file for holberton proyects
# put this script in /usr/bin with execute permissions
# feel free to edit the script with your preferences
# Author: @kael1706
# Contributor:
echo how many mains you need create?:
read n
echo .c or .py?:
read t
import_c=('#include <stdio.h>' '#include <stdlib.h>')
while ((n != 0))
do
 ((n = n - 1))
 if [ "$t" = ".py" ]; then
  touch "$n-main.py"
  echo '#!/usr/bin/python3' > "$n-main.py"
  echo $'namefunction = __import__(\'nameModule\').nameFunction\n'  >> "$n-main.py"
  echo "File $n-main.py created"
 else
  touch "$n-main.c"
  echo ${import_c[0]} > "$n-main.c"
  echo $'/**\n * main - check the code for Holberton School students.\n *\n * Return: 0\n*/' >> "$n-main.c"
  echo $'int main(void)\n{\n\treturn (0);\n}\n' >> "$n-main.c"
  echo "File $n-main.c created"
 fi
done
