#!/bin/bash
# this is hbtgm
# this script makes main file for holberton proyects
# put this script in /usr/bin with execute permissions
# feel free to edit the script with your preferences
# Author: @kael1706
# Contributor:
echo start index:
read s
echo end index:
read e
echo Do you want empty main?yes or no:
read empty
echo .c or .py?:
read t
import_c=('#include <stdio.h>' '#include <stdlib.h>')
while ((s <= e))
do
 if [ "$t" = ".py" ]; then
  touch "$s-main.py"
  echo '#!/usr/bin/python3' > "$s-main.py"
  if [ "$empty" = "no" ]; then
   echo $'namefunction = __import__(\'nameModule\').nameFunction'  >> "$s-main.py"
  fi
  echo "File $s-main.py created"
 else
  touch "$s-main.c"
  echo ${import_c[0]} > "$s-main.c"
  if [ "$empty" = "no" ]; then
   echo $'/**\n * main - check the code for Holberton School students.\n *\n * Return: 0\n*/' >> "$s-main.c"
   echo $'int main(void)\n{\n\treturn (0);\n}' >> "$s-main.c"
  fi
  echo "File $s-main.c created"
 fi
 ((s = s + 1))
done
